version: 2
jobs: 
  test:
    working_directory: ~/dir
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
              - ./node_modules
      - run:
          name: Run test
          command: yarn test --ci
      - run:
          name: Run type check
          command: yarn type-check
      - run:
          name: Run lint
          command: yarn lint

  deploy-storybook:
    working_directory: ~/dir
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
              - ./node_modules
      - run:
          name: Build storybook
          command: yarn docs:build
      - restore_cache:
          key: firebase-dependency-cache-{{ checksum "./functions/package.json" }}
      - run:
          name: Install Firebase dependencies
          command: cd ./functions && yarn install && cd ../
      - save_cache:
          key: firebase-dependency-cache-{{ checksum "./functions/package.json" }}
          paths:
              - ./functions/node_modules
      - run:
          name: Deploy storybook
          command: yarn docs:deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
            tags:
              only: /.*/
      - deploy-storybook:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)+/
